services:
  backend:
    build: .
    image: listenin:v1
    container_name: listenin
    restart: always
    # It remains internal to the Docker network.
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: listenin-nginx
    restart: always
    ports:
      - "80:80" # Map host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
